### ISSUE TITLE
🚀[Feature]: Configure the process using a config hierarchy

### ISSUE THREAD

**Issue by MariusStorhaug** [PSModule/Process-PSModule#144]
### Description

Configuration hierarchy:
Defaults -> Config file

Config file location: `.github/PSModule.yml`

Settings:

```yml
Name: <ModuleName> (repo name is used if not provided)
Path:
  Workspace: ${{ github.workspace }}
  SourceCode: src
  ModuleOutput: outputs/module
  DocsOutput: outputs/docs
  SiteOutput: outputs/site
Artifacts:
  ModuleArtifactName: module
  DocsArtifactName: docs
  AddArtifactToRelease: true
Tests:
  SkipSourceCode: false
  SkipModule: false
Publishing:
  DocsLocation: GithubPages
  AutoCleanPrereleases: true

```
