### ISSUE TITLE
🚀[Feature]: Make it possible to send env's into the workflow

### ISSUE THREAD

**Issue by MariusStorhaug** [PSModule/Process-PSModule#52]
### Description

The GitHub module needs a way to pass in secrets used for testing. We could connect the tests to keyvault and have the test reach out to get the secrets from the keyvault, but that is more infra than just adding a way to do it in the workflow itself.

## Idea

```yml
jobs:
  Process-PSModule:
    uses: PSModule/Process-PSModule/.github/workflows/workflow.yml@v3
    secrets: inherit
    with:
      SkipTests: SourceCode
      env: |
        TEST_APP_CLIENT_ID: ${{ secrets.TEST_APP_CLIENT_ID }}
        TEST_APP_PRIVATE_KEY: ${{ secrets.TEST_APP_PRIVATE_KEY }}
        TEST_FG_PAT: ${{ secrets.TEST_FG_PAT }}
        TEST_PAT: ${{ secrets.TEST_PAT }}
```

The env input on the workflow is then used as input to a job that runs at the start of the necessary jobs (i.e. tests) where we want to be able to send in some secrets.

The format is that of the normal `env:` property on the GH action syntax. Delimiter between key and value is the fist `:` (colon). The value behind should be trimmed, masked and stored in the corresponding env var (the name infront of the `:`.

**Comment by MariusStorhaug** [comment]
# Specification: Securely Passing Arbitrary Secrets to Reusable GitHub Workflows

## Summary
Implement a secure method for passing an unlimited number of arbitrary secrets to GitHub reusable workflows using asymmetric encryption (libsodium), allowing secrets to be managed without explicit declaration within the reusable workflow.

## Background
GitHub reusable workflows currently require all secrets to be explicitly declared, limiting flexibility when dynamically managing many secrets. To overcome this, encrypted variables (ciphertexts) will be passed through environment variables (`env`) and decrypted at runtime with a private key stored securely in GitHub secrets.

## Proposed Solution

### Workflow

#### Preparation
- Generate an asymmetric key pair (using libsodium).
- Store the private key securely as a GitHub secret (`PRIVATE_KEY_SECRET`).
- Encrypt each secret individually using the public key and store them as GitHub variables.

#### Workflow Structure

**Caller Workflow:**
```yaml
name: Caller Workflow
on: [workflow_dispatch]

env:
  ENCRYPTED_SECRET1: ${{ vars.ENCRYPTED_SECRET1 }}
  ENCRYPTED_SECRET2: ${{ vars.ENCRYPTED_SECRET2 }}

jobs:
  call-reusable-workflow:
    uses: org/repo/.github/workflows/reusable.yml@main
    secrets:
      PRIVATE_KEY_SECRET: ${{ secrets.PRIVATE_KEY_SECRET }}
```

**Reusable Workflow:**
```yaml
name: Reusable Workflow
on:
  workflow_call:
    secrets:
      PRIVATE_KEY_SECRET:
        required: true

jobs:
  decrypt-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Decrypt Secrets
        run: |
          npm install -g sodium-cli
          PRIVATE_KEY="${{ secrets.PRIVATE_KEY_SECRET }}"

          SECRET1=$(echo "$ENCRYPTED_SECRET1" | sodium-cli seal-open "$PRIVATE_KEY")
          SECRET2=$(echo "$ENCRYPTED_SECRET2" | sodium-cli seal-open "$PRIVATE_KEY")

          echo "::add-mask::$SECRET1"
          echo "::add-mask::$SECRET2"
```

## Security Considerations
- **Never expose** decrypted secrets in logs; always use GitHub Actions' masking feature (`::add-mask::`).
- Regularly rotate encryption keys.
- Only store ciphertext (encrypted data) publicly or in repository variables.
- Private keys must be securely managed as GitHub secrets.

## Benefits
- Enables unlimited, dynamic secret management.
- Ensures secrets are managed securely and flexibly.
- Eliminates the need to explicitly declare each secret in the reusable workflow, reducing workflow complexity.

## Acceptance Criteria
- A functional example demonstrating secure encryption, environment variable passing, and runtime decryption.
- Documentation detailing the key generation, encryption, and decryption process.
- Explicit demonstration of secret masking to ensure workflow security compliance.
