### ISSUE TITLE
🚀[Feature]: Have the option of not deleting prereleases

### ISSUE THREAD

**Issue by mchave3** [PSModule/Process-PSModule#81]
### Description

In connection with Process-PSModule, would it be possible to have an option not to delete prereleases in the Github release list ? 
I think it would be nice to have the choice of keeping them or not, so as to have at least a history of changes in Github.

**Comment by MariusStorhaug** [comment]
@mchave3 Already working on the co-location. Seems to be fine to move. Will do it bit by bit. The technical stuff now and the practical stuff in a while. Need to update documentation aswell, but can likely just update when I know more about the sturucture it will have in the end.

**Comment by mchave3** [comment]
Perfect, can't wait to see these changes.

**Comment by MariusStorhaug** [comment]
The implementation is taking abit longer than expected. What I am trying to change now on the design is:
- Use of nested workflows within `Process-PSModule` as you cannot co-locate the action code. When using an action, the action repo is checked out; when using a reusable workflow, the workflow file is expanded into your workflow (no code checkout or ability to reference anything in the workflow repo). So a bit of a snag on that.
- Allow for parallel testing of PSModule tests and test suites from the module. Design im going for here is to use subfolders in the `tests` folder to be one test suite, and each of these gets its own job, so they can be processed in parallel. Status and report aggregation would happen after it (similarly as it is today, just needs more functionality later, i.e. combining JaCoCo tests to get full coverage reporting.
- Set up the settings file for it.

**Comment by MariusStorhaug** [comment]
@mchave3 Sorry for taking so long, but there are so many improvements that are coming with v4.

In regards to your question of not doing cleanup of prerelease; that has been in there all along.. Its weird I didnt remember. There are two things you can do to control this:

1. Use the default place of `ConfigurationFile` thats present in Publish-PSModule.

```yaml
  ConfigurationFile:
    description: The path to the configuration file. Settings in the configuration file take precedence over the action inputs.
    required: false
    default: .github/auto-release.yml # This is the configured name, its just a copy paste issue from the "Auto-Release" action that was made first.
```

This will take all the settings that you would otherwise send to the action, and would configure it that way.

2. Configure the `AutoCleanup` property in the file.

```yaml
  AutoCleanup:
    description: Control whether to automatically delete the prerelease tags after the stable release is created.
    required: false
    default: 'true'
```

All of this is taken from the action.yml from [Publish-PSModule](https://github.com/PSModule/Publish-PSModule). 

Just so you are also up to date with the v4 of Process-PSModule, it is on its way this weekend I believe. Will refactor so that all configurable settings in the process use another file called `.github/PSModule.yml` and contain sections similar to what was described above. What is taking time right now is aligning design of all actions to use a `workdirectory` parameter to determine "root" folder of the repo. Just refactoring so that pathing is dynamic based on that. Why? One of the settings will allow you to modify the folderstructure as you see fit. 

I am also aligning a new naming convention on envvars, so they "never" clobber each other. Names of envvars that link action inputs with main.ps1 will be following `<ORG_NAME>_<REPO_NAME>_INPUT_*`.

Most importantly for me, is the dynamic parallelism of tests. It will now read folders from the `tests` folder and make multiple jobs of that. If there is only a file and no folders, it will still work as now with one job for testing the module.
